name: print my name

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  console:
    runs-on: ubuntu-latest
    steps:
       - uses: Print Name
      - name: Checkout Repositore

        run: echo "misk sawallha**"
        shell: bash
