name: Emoji Checker
on:
  push:
    branches:
      - main
pull_request:
     -main
  workflow_dispatch:
jobs:
  console:
    runs-on: ubuntu-latest
    steps:
      - name: print name
       - uses: actions/checkout@v2
       run : echo "misk sawallha"
      - name: Check Emoji Shortcodes
      - shell  : bash
