name: Emoji Checker
on:
  push:
    branches:
      - main
pull_request:
     -main
jobs:
  console:
    runs-on: ubuntu-latest
    steps:
     - uses: actions/checkout@v2
      - name: print name
      - run : echo "misk sawallha"
      - shell  : bash
