name: print my name

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  console:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Repository
        uses: actions/checkout@v2

      - name: Print Name
        run: echo "misk sawallha**"
